openapi: 3.0.3

info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.0.0

servers:
- url: /

tags:
- name: WorkspaceService
  description: ワークスペースに関する操作

paths:
  /api/{organization_id}/platform/workspaces:
    get:
      tags:
      - WorkspaceService
      summary: List returns list of workspaces
      operationId: WorkspaceService_List
      parameters:
      - name: organization_id
        in: path
        required: true
        schema:
          type: string
      - name: workspace_name
        in: query
        description: the workspace's name.
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspaceList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    post:
      tags:
      - WorkspaceService
      summary: Create creates an workspace
      operationId: WorkspaceService_Create
      parameters:
      - name: organization_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workspace'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspace'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'

components:
  schemas:
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    workspace:
      title: workspace is a definition of Workspace resource.
      type: object
      properties:
        workspace_id:
          type: string
        workspace_name:
          type: string
    workspaceList:
      title: workspaceList is list of Workspace resources.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/workspace'
