#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#---- exastro-common-auth-namespace.yaml
---
#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: Namespace
metadata:
  name: exastro-common-auth


#---- exastro-common-auth-env.yaml
---
#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: exastro-common-auth-env
  namespace: exastro-common-auth
data:
  EXASTRO_KEYCLOAK_HOST: ""
  EXASTRO_KEYCLOAK_PROTOCOL: "https"
  EXASTRO_KEYCLOAK_PORT: "32001"

#---- exastro-common-auth-secret.yaml
---
#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: Secret
metadata:
  name: exastro-common-auth-secret
  namespace: exastro-common-auth
stringData:
  GATEWAY_CRYPTO_PASSPHRASE: ""
  KEYCLOAK_USER:  "admin"
  KEYCLOAK_PASSWORD: "admin"
  EPOCH_PASSWORD: ""
#---- common-api.yaml
---
#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-api-conf
  namespace: exastro-common-auth
data:
  api_authc_infra.conf: |
    TZ='Asia/Tokyo'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api
  namespace: exastro-common-auth
spec:
  selector:
    matchLabels:
      name: common-api
  replicas: 1
  template:
    metadata:
      labels:
        name: common-api
    spec:
      volumes:
      - name: common-api-conf
        configMap:
          name: common-api-conf
      containers:
      - name: common-api
        image: exastro/exastro-common-auth-api:0.1.0_20220222_1100
        env:
        - name: CONFIG_API_AUTHC_INFRA_PATH
          value: "/etc/exastro-common-auth/common-api/api_authc_infra.conf"
        - name: FLASK_ENV
          value: "development"
        - name: API_AUTHC_INFRA_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: EXASTRO_KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: exastro-common-auth-secret
              key: KEYCLOAK_USER
        - name: EXASTRO_KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exastro-common-auth-secret
              key: KEYCLOAK_PASSWORD
        - name: EXASTRO_KEYCLOAK_MASTER_REALM
          value: "master"
        - name: GATEWAY_CRYPTO_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: exastro-common-auth-secret
              key: GATEWAY_CRYPTO_PASSPHRASE
        - name: EXASTRO_KEYCLOAK_HOST
          valueFrom:
            configMapKeyRef:
              name: exastro-common-auth-env
              key: EXASTRO_KEYCLOAK_HOST
        - name: EXASTRO_KEYCLOAK_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: exastro-common-auth-env
              key: EXASTRO_KEYCLOAK_PROTOCOL
        - name: EXASTRO_KEYCLOAK_PORT
          valueFrom:
            configMapKeyRef:
              name: exastro-common-auth-env
              key: EXASTRO_KEYCLOAK_PORT
        - name: API_KEYCLOAK_HOST
          value: "keycloak"
        - name: API_KEYCLOAK_PROTOCOL
          value: "http"
        - name: API_KEYCLOAK_PORT
          value: "8080"
        volumeMounts:
        - name: common-api-conf
          mountPath: /etc/exastro-common-auth/common-api

---

apiVersion: v1
kind: Service
metadata:
  name: common-api
  labels:
    name: common-api
  namespace: exastro-common-auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: common-api

#---- gateway-httpd.yaml
---
#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-httpd
  namespace: exastro-common-auth
spec:
  selector:
    matchLabels:
      name: gateway-httpd
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway-httpd
    spec:
      volumes:
      containers:
      - name: gateway-httpd
        image: exastro/exastro-common-auth-gateway-httpd:0.1.0_20220222_1100

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-httpd
  labels:
    app: gateway-httpd
  namespace: exastro-common-auth
spec:
  ports:
  - name: https
    port: 32000
    targetPort: 32000
    nodePort: 32000
  selector:
    name: gateway-httpd
  type: NodePort

#---- keycloak.yaml
---
#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: exastro-common-auth
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  labels:
    app: keycloak
  namespace: exastro-common-auth
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 32001
  selector:
    app: keycloak
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: exastro-common-auth
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:15.0.2
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: exastro-common-auth-secret
              key: KEYCLOAK_USER
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exastro-common-auth-secret
              key: KEYCLOAK_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
