openapi: 3.0.3

info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.0.0

servers:
- url: /

tags:
- name: WorkspaceService
  description: ワークスペースに関する操作
- name: UsersService
  description: ユーザーに関する操作
- name: InternalWorkspaceService
  description: ワークスペースに関する操作(内部用)

paths:
  "/api/{organization_id}/platform/workspaces":
      $ref: './paths/workspaces.yaml'
  "/api/{organization_id}/platform/users/{user_id}/workspaces":
      $ref: './paths/users_workspaces.yaml'
  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/roles":
      $ref: './paths/workspaces_roles.yaml'
  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/users":
      $ref: './paths/workspaces_users.yaml'
  "/internal-api/{organization_id}/platform/users/{user_id}/workspaces":
      $ref: './paths/users_workspaces.yaml'

components:
  schemas:
    $ref: './schemas/_schemas.yaml'
