openapi: 3.0.3
info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.0.0
servers:
- url: /
tags:
- name: WorkspaceService
  description: ワークスペースに関する操作
- name: UsersService
  description: ユーザーに関する操作
- name: InternalWorkspaceService
  description: ワークスペースに関する操作(内部用)
paths:
  /api/{organization_id}/platform/workspaces:
    get:
      tags:
      - WorkspaceService
      summary: List returns list of workspaces
      operationId: workspace_list
      parameters:
      - name: organization_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_name
        in: query
        description: the workspace's name.
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspaceList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-openapi-router-controller: controllers.workspace_service_controller
    post:
      tags:
      - WorkspaceService
      summary: Create creates an workspace
      operationId: workspace_create
      parameters:
      - name: organization_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workspace'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspace'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-openapi-router-controller: controllers.workspace_service_controller

  /api/{organization_id}/platform/users/{user_id}/workspaces:
    get:
      tags:
      - UsersService
      summary: List returns list of workspaces
      operationId: user_workspace_list
      parameters:
      - name: organization_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workspaceList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-openapi-router-controller: controllers.users_service_controller

  /internal-api/{organization_id}/platform/workspaces/{workspace_id}/roles:
    get:
      tags:
      - InternalWorkspaceService
      summary: Get all roles for the workspace
      operationId: workspace_role_list
      parameters:
      - name: organization_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/roleList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-openapi-router-controller: controllers.internal_service_controller
  /internal-api/{organization_id}/platform/workspaces/{workspace_id}/users:
    get:
      tags:
      - InternalWorkspaceService
      summary: Get all users for the workspace
      operationId: workspace_user_list
      parameters:
      - name: organization_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-openapi-router-controller: controllers.internal_service_controller
components:
  schemas:
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    workspace:
      title: workspace is a definition of Workspace resource.
      type: object
      properties:
        workspace_id:
          type: string
        workspace_name:
          type: string
      example:
        workspace_id: workspace_id
        workspace_name: workspace_name
    workspaceList:
      title: workspaceList is list of Workspace resources.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/workspace'
      example:
        items:
        - workspace_id: workspace_id
          workspace_name: workspace_name
        - workspace_id: workspace_id
          workspace_name: workspace_name
    role:
      title: role is a definition of Role resource.
      type: object
      properties:
        workspace_id:
          type: string
        workspace_name:
          type: string
      example:
        workspace_id: workspace_id
        workspace_name: workspace_name
    roleList:
      title: roleList is list of Role resources.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/role'
      example:
        items:
        - workspace_id: workspace_id
          workspace_name: workspace_name
        - workspace_id: workspace_id
          workspace_name: workspace_name
    user:
      title: user is a definition of User resource.
      type: object
      properties:
        workspace_id:
          type: string
        workspace_name:
          type: string
      example:
        workspace_id: workspace_id
        workspace_name: workspace_name
    userList:
      title: userList is list of User resources.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/user'
      example:
        items:
        - workspace_id: workspace_id
          workspace_name: workspace_name
        - workspace_id: workspace_id
          workspace_name: workspace_name

